[drivers]
bigquery = "https://pypi.org/project/adbc-driver-bigquery/"
databricks = "https://github.com/adbc-drivers/databricks"
duckdb = "https://github.com/adbc-drivers/duckdb"
flightsql = "https://pypi.org/project/adbc-driver-flightsql/"
mssql = "https://github.com/adbc-drivers/mssql"
mysql = "https://github.com/adbc-drivers/mysql"
postgresql = "https://pypi.org/project/adbc-driver-postgresql/"
snowflake = "https://pypi.org/project/adbc-driver-snowflake/"
sqlite = "https://pypi.org/project/adbc-driver-sqlite/"
trino = "https://github.com/adbc-drivers/trino"
